language: cpp
compiler:
  - gcc

install:
  - travis_wait ./cmake-compile.sh
  - travis_wait ./petsc-compile.sh

script:
   - ls -l
   - $HOME/cmake-3.2.3/bin/cmake --version
   - cd $HOME/cmake-3.2.3/bin/
   - ls -l
   - ./cmake --version
