language: cpp
compiler:
  - gcc

install:
  - apt-get update -q
  - apt-get install 
  - travis_wait ./cmake-compile.sh
  - travis_wait ./petsc-compile.sh

script:
   - cmake-3.2.3/bin/cmake --version
