language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"

install:
  - pip install numpy

before_script:
  - sudo apt-get update -q
  - sudo apt-get install pandoc
  - sudo apt-get install texlive-latex-base

script:
  - pandoc -N name.md --latex-engine=pdflatex -o name.pdf
  - python --version
  - python py-ex/ex.py
  - cat ./update.sh
  - ls -l ./update
  - ./update.sh

after_success:
  - ./update.sh
