language: python
python:
  - "2.7"

os:
  - linux
  - osx

install:
  - cmake --version
  - sudo apt-get update -q
  - sudo apt-get install cmake

before_script:
  - cmake --version
 
script:
   - gcc --version
