language: cpp
compiler:
  - gcc

sudo: required

install:
  - sudo apt-get update -q
  - sudo apt-get install gfortran
  - travis_wait ./petsc-compile.sh

script:
   - ls -l
   - $HOME/cmake-3.2.3/bin/cmake --version
   - gfortran --version
