language: python
python:
  - "2.7"

os:
  - linux
  - osx

install:
  - sudo apt-get update -q
  - sudo apt-get install pandoc
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install texlive-latex-recommended

before_script:
  - python --version
 
script:
  - pandoc -N name.md --latex-engine=pdflatex -o name.pdf
  - pandoc -N structure.md --latex-engine=pdflatex -o structure.pdf
  - pandoc -N to-talk.md --latex-engine=pdflatex -o to-talk.pdf

after_success:
  - ./update.sh
